### ISSUE TITLE
Cant login using reroll account

### ISSUE THREAD

**Issue by IlhamriSKY** [Mila432/Grand-Summoners-Python-Bot#4]
after i edit
```
self.app_version=31
self.master_version=404
self.resource_version=183
self.platform_type = 1
```

i cant login using gmail and pass that come at reroll.csv

**Comment by Mila432** [comment]
fixed https://github.com/Mila432/Grand-Summoners-Python-Bot/commit/28677165c7c38c6aeee97a4d2cda90058350d40f

**Comment by IlhamriSKY** [comment]
> fixed [2867716](https://github.com/Mila432/Grand-Summoners-Python-Bot/commit/28677165c7c38c6aeee97a4d2cda90058350d40f)

```
Traceback (most recent call last):
  File "C:\Python27\Grand-Summoners-Python-Bot\api.py", line 331, in <module>
    a.reroll()
  File "C:\Python27\Grand-Summoners-Python-Bot\api.py", line 319, in reroll
    self.eventshop_page(2008000)
  File "C:\Python27\Grand-Summoners-Python-Bot\api.py", line 82, in eventshop_page
    return self.callAPI({"app_hash":self.app_hash,"app_version":self.app_version,"event_id":event_id,"master_version":self.master_version,"platform_type":self.platform_type,"resource_version":self.resource_version,"user_unique_id":""})
  File "C:\Python27\Grand-Summoners-Python-Bot\api.py", line 165, in callAPI
    body=json.loads(r.content)['body']
KeyError: 'body'
```

**Comment by IlhamriSKY** [comment]
![image](https://user-images.githubusercontent.com/18723904/71279901-77c4c800-238c-11ea-9e67-b1a03107f1f6.png)

**Comment by InCrIpTiOn** [comment]
It's because you're rerolling too quickly and are getting rate limited. Try using a proxy or wait 10 minutes to try again

**Comment by IlhamriSKY** [comment]
> It's because you're rerolling too quickly and are getting rate limited. Try using a proxy or wait 10 minutes to try again

okey solved then,

and how to get benner id and unit ids?

i can packet sniffing but never get that ids

**Comment by InCrIpTiOn** [comment]
When you click on the summon tab a request to retrieve the banners is completed. Those will give you all the detail you need

**Comment by InCrIpTiOn** [comment]
If you need to decrypt your packet during interception you can write a custom script using a MITM proxy like mitmproxy for python

**Comment by IlhamriSKY** [comment]
> When you click on the summon tab a request to retrieve the banners is completed. Those will give you all the detail you need

are you have discord or something?, 
I will ask many questions about this

**Comment by IlhamriSKY** [comment]
> If you need to decrypt your packet during interception you can write a custom script using a MITM proxy like mitmproxy for python

**I try this** 

`getapiversion = "anjO9AupBu74vdORIFevgOfmwVvai/puDBqLHx6qLozE0j05m/V9ztNJXC4f7I2yhEH2f7gLWI71tH7gUqnW0G3PMTJc6dD85PhZPfBdYK8Vhp6nBjdyFBkBFwRROyoRUbV3Hy3xVPMRwvQ7n/CC454Y4VhMNX67HZOyiKcYfmQFUVAskp0h4lSDQYyQ1IwtG6aY+opI2HnqbUMpsWy/rTJLsFOp+9mOxTNA8i5+Ue2OUP0NhZFua1Q93yur4FME8rLIV60y93we3bkoUMuuwg=="`

`a.decrypt(getapiversion)
`
**return** 
`{"app_hash": "", "app_version": 31, "master_version": 404, "platform_type": 1, "resource_version": 183, "scenario_master_version": 120, "user_unique_id": ""}`


and after i use packet sniffing for gacha i get body 
`gacha2 = "VCezcblqCbQtQhF1Vn7oIfAZViboXmPZ7QPXB397IASvE5KeADllsIlZI43xyqnC0kF5JhtwSQbqOgtyv8JSh+WRH6UFST1It27K8MEn2q/JQxRtqew9mlUUZz3ngB2cDNOe8RCHzkzfYRCpFxqYU2ALrdh7CdRC/lgB29c+pBni03BfgJMj1QkDb98vXXmTGj5Q2euQTerd8Pe6fCXpPZXeDq28b2JrIwf9LMXB547lQxbU1Q7bHNn9NXweOJs8D7Cr3k5CwOTMRbrcp4LM1/ngbZqlCt+7zupj4Jp3we5Axz1c4zU0tn8dPqqJXp74zdsK37qchbatzBLI9XuytvejtYys0NTj+WJ9j2IWI1URk4ZIoftwIFlfRYzqIo3K"`

and do same thing
`a.decrypt(gacha2 )
`

**it return error**

> ValueError: Input is not padded or padding is corrupt
 
![image](https://user-images.githubusercontent.com/18723904/71285659-579b0600-2398-11ea-8bba-c0cae2d7e299.png)
