### ISSUE TITLE
Key to open encrypted_app.db 

### ISSUE THREAD

**Issue by haivle** [Mila432/Grand-Summoners-Python-Bot#7]
Hi @Mila432, 

Can you give me a hint on how to get the encryption key to open encrypted_app.db? 
I've try masterdata_key returned from game_init response but without any success.

Thank you

**Comment by InCrIpTiOn** [comment]
You should try and get it from sniffing the packets from a real game app. This is an old repository

**Comment by haivle** [comment]
@InCrIpTiOn do you know how to update unit_master.py? I'm trying to decrypt encrypted_app.db, but I don't know how to decrypt that.

**Comment by haivle** [comment]
I figured it by myself, thank you
